# Generated by Django 5.0.4 on 2024-04-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filmwork",
            options={"verbose_name": "Film", "verbose_name_plural": "Films"},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "Genre", "verbose_name_plural": "Genres"},
        ),
        migrations.AlterModelOptions(
            name="genrefilmwork",
            options={
                "verbose_name": "Genre-Film",
                "verbose_name_plural": "Genres-Films",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "Person", "verbose_name_plural": "Persons"},
        ),
        migrations.AlterModelOptions(
            name="personfilmwork",
            options={
                "verbose_name": "Person-Film",
                "verbose_name_plural": "Persons-Films",
            },
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="description",
            field=models.TextField(
                blank=True, default="Нет описания", verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="file_path",
            field=models.TextField(blank=True, default="", verbose_name="file_path"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.TextField(
                blank=True,
                choices=[
                    ("actor", "Actor"),
                    ("director", "Director"),
                    ("writer", "Writer"),
                ],
                default="",
                verbose_name="role",
            ),
        ),
    ]
