version: '3.8' 

# То из чего будет собираться Docker.
services:
  django:
    build:
      context: .
    

    # Когда какая-то ПАПКА из локальной машины перекидывается в Docker.
    # То есть, все изменения, которые мы делаем локально, то все изменения сразу оказываются внутри контейнера.
    volumes:
      - "./movies_admin:/movies_admin"
    
    # Необходимо для соединения контейнера Django с контейнером Database.
    environment:
      - DB_HOST=database
      - DB_NAME=movies_database
      - DB_USER=app
      - DB_PASSWORD=123qwe
      - SECRET_KEY='django-insecure-8h%wg+drqmqjkw$8wm7#)#%*fb3b%(-e!-kbdth^#9u)23u!48'
    
    command:
      sh -c "uwsgi --ini /movies_admin/uwsgi.ini"
    
    # Не запускать контейнер с PostgreSQL пока не соберется контейнер с Django.
    depends_on:
      - database
  
  # Не нужно создавать свой собственный image, берем стандартный с Docker Hub.
  database:

    image: postgres:16

    environment:
      - DB_NAME=movies_database
      - DB_USER=app
      - DB_PASSWORD=123qwe
    
    # перебрасываем существующую бд, созданную в другом docker контейнере в новый контейнер
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
  
  # создаем контейнер nginx из готово образа и прикручиваем измененный конфиг
  # копируем статику из корневого каталога джанго (необходимо создать папку staticfiles перед контейнеризацией) в /etc/nginx/
  # тут скопировали только статику админки, так как на конце указали admin
  nginx:
    image: nginx:latest
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./movies_admin/movies_admin/staticfiles/admin:/etc/nginx/movies_admin/movies_admin/staticfiles/admin"
      - "./movies_admin/movies_admin/staticfiles/rest_framework:/etc/nginx/movies_admin/movies_admin/staticfiles/rest_framework"
    ports:
      - "80:80"
    depends_on:
      - django
  
